### ISSUE TITLE
xanautomail

### ISSUE THREAD

**Issue by Lindseysig** [Xruptor/xanAutoMail#1]
ya, as I had posted on other site about auto open button not working on AH items in mail..works just fine on items sent from an alt. as you see in screen shot you can see the button and all, but when you click on it to open mail..it just doesnt do anything for AH items..as i said I disabled all my other addons and it still did it..=( not a big deal if its 1 or 2 items but more than that its a a pain..its why I got the addon =) hope this helps
![wowscrnshot_101716_144719](https://cloud.githubusercontent.com/assets/22945467/19537672/df90cee2-961e-11e6-8421-067421c63ea3.jpg)

**Comment by Xruptor** [comment]
Great! I will be glad to work with you to get this fixed.  I have an idea of whats going on and it's rather silly if it is.  What I'm going to do is program a special version of the addon that will record some debugging for me.  I will use this debugging to see what's going on with your end.  I will also add the fixes I think will fix the issues you are having.  So hopefully I knock out two birds with one stone! :)  Let me write up that version for you.  I will keep you posted.

**Comment by Lindseysig** [comment]
ok..cool..thanks alot

**Comment by Xruptor** [comment]
Okay I need you to try this attached version.  Please note that this is a special debug version and I'm going to make changes to it constantly until it's fixed for you.  Please give it a try and let me know if everything works for you.  If not then I need to make another adjustment.

[xanAutoMail.zip](https://github.com/Xruptor/xanAutoMail/files/545781/xanAutoMail.zip)

**Comment by Lindseysig** [comment]
ok..sorry where do I put this my wow folder?

**Comment by Lindseysig** [comment]
ok..I figured it out and got it in and it works =)

**Comment by Xruptor** [comment]
Okay that's good.  You had no issues whatsoever?  I suspected part of the problem was already read mail, which I had stated before.  Please keep using it for one or two days and then get back to me.  If it works as it should then I will make the final preparations to push it to release for everyone.

**Comment by Lindseysig** [comment]
yup..no issues and ok will do

**Comment by Lindseysig** [comment]
still working fine on my end =)

**Comment by Xruptor** [comment]
Great then I will finalize the changes.  Thanks for your assistance!

**Comment by Lindseysig** [comment]
welcome and thanks for the great add on
